# Generated by Django 4.2.13 on 2024-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_customer_profile_pic_alter_customer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
